
###服务启动端口号
server:
  port: 8088


spring:
###数据库相关连接
  datasource:
    username: root
    password: api@yfwkj.com
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.248:3306/yfwkj?useUnicode=true&characterEncoding=UTF-8