
###服务启动端口号
server:
  port: 8088


spring:
###数据库相关连接
  datasource:
    username: root
    password: api@yfwkj.com
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.248:3306/yfwkj?useUnicode=true&characterEncoding=UTF-8

    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: E:/sundry/uploadfile
      max-file-size: 50MB
      max-request-size: 100MB
      resolve-lazily: false